apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: risc4n5bw-python 
  janus-idp.io/tekton: risc4n5bw-python
  backstage.io/kubernetes-id: risc4n5bw-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: risc4n5bw-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml